Repository networktocode/genieparser, pull requests merged in 2020-09, with the labels that each got.

#45 Create parser for show ap rf-profile summary
  changelog/undistributed.rst
  src/genie/libs/parser/iosxe/show_ap.py
  src/genie/libs/parser/iosxe/tests/test_show_ap.py
Labels: assigned, cisco_pr, completed, complexity: low, identified, raw_data

#14 Create parser for show_cts_sxp_connections_brief
  changelog/undistributed.rst
  src/genie/libs/parser/iosxe/show_cts.py
  src/genie/libs/parser/iosxe/tests/test_show_cts.py
Labels: assigned, cisco_pr, completed, complexity: low, identified

#37 Parser for show lisp site
  changelog/undistributed.rst
  src/genie/libs/parser/iosxe/show_lisp.py
  src/genie/libs/parser/iosxe/tests/test_show_lisp.py
Labels: assigned, cisco_pr, completed, complexity: low, identified, raw_data

#42 Create Parser for iosxe/show_cts_role-based_counters
  changelog/undistributed.rst
  src/genie/libs/parser/iosxe/show_cts.py
  src/genie/libs/parser/iosxe/tests/test_show_cts.py
Labels: assigned, cisco_pr, completed, complexity: low, identified, raw_data

#110 Adding parser for iosxe show wireless fabric summary
  changelog/undistributed/changelog_show_wireless_fabric_summary_20200925181528.rst
  src/genie/libs/parser/iosxe/show_wireless.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessFabricSummary/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowWirelessFabricSummary/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessFabricSummary/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low, identified

#108 Parser created for iosxe show chassis
  changelog/undistributed/changelog_show_chassis_20200922164850.rst
  src/genie/libs/parser/iosxe/show_chassis.py
  src/genie/libs/parser/iosxe/tests/ShowChassis/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowChassis/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowChassis/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low, identified

#97 Parser created for iosxe show snmp group
  changelog/undistributed/changelog_show_snmp_20200917223919.rst
  src/genie/libs/parser/iosxe/show_snmp.py
  src/genie/libs/parser/iosxe/tests/ShowSnmpGroup/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowSnmpGroup/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowSnmpGroup/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low, identified

#96 Adding parser for IOSXE show_wireless_mobility_ap-list
  changelog/undistributed/changelog_show_wireless_mobility_ap-list20200916155500.rst
  src/genie/libs/parser/iosxe/show_wireless.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessMobilityApList/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowWirelessMobilityApList/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessMobilityApList/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, raw_data

#65 Added parser for iosxe/show_wlan_summary
  changelog/changelog_show_wlan_summary20200919142850.rst
  src/genie/libs/parser/iosxe/show_wlan.py
  src/genie/libs/parser/iosxe/tests/ShowWlanSummary/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowWlanSummary/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowWlanSummary/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low, identified, raw_data

#60 Parser for iosxe/show_ap_led-brightness-level_summary
  changelog/changelog_show_ap_dot11_5ghz_channel.rst
  changelog/changelog_show_ap_dot11_5ghz_summary.rst
  changelog/changelog_show_ap_led_brightness_level_summary20200919135134.rst
  src/genie/libs/parser/iosxe/show_ap.py
  src/genie/libs/parser/iosxe/tests/ShowApDot115GhzChannel/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowApDot115GhzChannel/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowApDot115GhzChannel/cli/equal/golden_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowApDot115GhzSummary/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowApDot115GhzSummary/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowApDot115GhzSummary/cli/equal/golden_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowApLedBrightnessLevelSummary/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowApLedBrightnessLevelSummary/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowApLedBrightnessLevelSummary/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low, identified, raw_data
