Repository networktocode/genieparser, pull requests merged in 2020-10, with the labels that each got.

#103 Parser for show wireless fabric client summary
  changelog/undistributed/changelog_show_wireless_fabric_client_summary-list20200916232000.rst
  src/genie/libs/parser/iosxe/show_wireless.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessFabricClientSummary/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowWirelessFabricClientSummary/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessFabricClientSummary/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low, identified

#99 Adding parser for IOSXE/show wireless mobility summary
  changelog/undistributed/changelog_show_wireless_mobility_summary_20200916164800
  src/genie/libs/parser/iosxe/show_wireless.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessMobilitySummary/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowWirelessMobilitySummary/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessMobilitySummary/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, raw_data

#93 Created parser for iosxe show snmp user
  changelog/undistributed/changelog_show_snmp_user-list20200916174100.rst
  src/genie/libs/parser/iosxe/show_snmp.py
  src/genie/libs/parser/iosxe/tests/ShowSnmpUser/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowSnmpUser/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowSnmpUser/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low, identified

#66 Added parser for iosxe/show_wireless_client_summary
  changelog/changelog_show_wireless_client_summary20200919143540.rst
  src/genie/libs/parser/iosxe/show_wireless.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessClientSummary/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowWirelessClientSummary/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessClientSummary/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low, identified, raw_data

#109 PR#265 Adding parser for iosxe show romvar
  changelog/undistributed/changelog_show_romvar_20200922195632.rst
  src/genie/libs/parser/iosxe/show_romvar.py
  src/genie/libs/parser/iosxe/tests/ShowRomvar/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowRomvar/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowRomvar/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: medium, identified

#123 PR#288 Modified show class-map to account for specific name
  changelog/undistributed/changelog_show_class-map_20201006154026.rst
  src/genie/libs/parser/iosxe/show_class.py
  src/genie/libs/parser/iosxe/tests/ShowClassMap/cli/equal/golden_arguments_output.json
  src/genie/libs/parser/iosxe/tests/ShowClassMap/cli/equal/golden_output1_expected.py
  src/genie/libs/parser/iosxe/tests/ShowClassMap/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowClassMap/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low, identified

#113 PR#273 Parser created for iosxe show wireless cts summary
  changelog/undistributed/changelog_show_wireless_cts_summary_20200930195542.rst
  src/genie/libs/parser/iosxe/show_wireless.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessCtsSummary/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowWirelessCtsSummary/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessCtsSummary/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low, identified

#112 PR#276 Parser created for iosxe show cts
  changelog/undistributed/changelog_show_cts_20200930044153.rst
  src/genie/libs/parser/iosxe/show_cts.py
  src/genie/libs/parser/iosxe/tests/ShowCts/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowCts/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowCts/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: medium, identified

#122 PR#286 Parser created for iosxe show wireless profile policy detailed
  changelog/undistributed/changelog_show_wireless_profile_policy_detailed_20201002232808.rst
  src/genie/libs/parser/iosxe/show_wireless.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessProfilePolicyDetailed/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowWirelessProfilePolicyDetailed/cli/equal/golden_output_arguments.json
  src/genie/libs/parser/iosxe/tests/ShowWirelessProfilePolicyDetailed/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessProfilePolicyDetailed/cli/equal/golden_output_output.txt
Labels: assigned, completed, complexity: medium, identified

#64 PR#254 create Parser for iosxe/show_ap_cdp_neighbor
  changelog/changelog_show_ap_cdp_neighbor20200919140508.rst
  src/genie/libs/parser/iosxe/show_ap.py
  src/genie/libs/parser/iosxe/tests/ShowApCdpNeighbor/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowApCdpNeighbor/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowApCdpNeighbor/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low, identified, raw_data

#124 PR#290 IOSXE/show redundancy switchover history
  changelog/undistributed/changelog_show_redundancy_switchover_history_20201007143119.rst
  src/genie/libs/parser/iosxe/show_redundancy.py
  src/genie/libs/parser/iosxe/tests/ShowRedundancySwitchoverHistory/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowRedundancySwitchoverHistory/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowRedundancySwitchoverHistory/cli/equal/golden_output_output.txt
Labels: cisco_pr, completed

#125 PR#293 Created parser for iosxe show wlan all
  changelog/undistributed/changelog_show_wlan_all_20201009223949.rst
  src/genie/libs/parser/iosxe/show_wlan.py
  src/genie/libs/parser/iosxe/tests/ShowWlanAll/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowWlanAll/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowWlanAll/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: medium, identified

#139 PR#310 IOSXE/show wireless stats mobility
  changelog/undistributed/changelog_show_wireless_stats_mobility_20201022141722.rst
  src/genie/libs/parser/iosxe/show_wireless.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessStatsMobility/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowWirelessStatsMobility/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessStatsMobility/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low, identified, raw_data

#140 PR#311 IOSXE/show ap tag summary
  changelog/undistributed/changelog_show_ap_tag_summary_20201022183850.rst
  src/genie/libs/parser/iosxe/show_ap.py
  src/genie/libs/parser/iosxe/tests/ShowApTagSummary/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowApTagSummary/cli/equal/golden_output_2_expected.py
  src/genie/libs/parser/iosxe/tests/ShowApTagSummary/cli/equal/golden_output_2_output.txt
  src/genie/libs/parser/iosxe/tests/ShowApTagSummary/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowApTagSummary/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low, identified, raw_data

#126 PR#295 IOSXE/show avc sd service info summary
  changelog/undistributed/changelog_show_avc_sd-service_info_summary_20201007165908.rst
  src/genie/libs/parser/iosxe/show_avc.py
  src/genie/libs/parser/iosxe/tests/ShowAvcSdServiceInfoSummary/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowAvcSdServiceInfoSummary/cli/equal/golden_output_2_expected.py
  src/genie/libs/parser/iosxe/tests/ShowAvcSdServiceInfoSummary/cli/equal/golden_output_2_output.txt
  src/genie/libs/parser/iosxe/tests/ShowAvcSdServiceInfoSummary/cli/equal/golden_output_3_expected.py
  src/genie/libs/parser/iosxe/tests/ShowAvcSdServiceInfoSummary/cli/equal/golden_output_3_output.txt
  src/genie/libs/parser/iosxe/tests/ShowAvcSdServiceInfoSummary/cli/equal/golden_output_4_expected.py
  src/genie/libs/parser/iosxe/tests/ShowAvcSdServiceInfoSummary/cli/equal/golden_output_4_output.txt
  src/genie/libs/parser/iosxe/tests/ShowAvcSdServiceInfoSummary/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowAvcSdServiceInfoSummary/cli/equal/golden_output_output.txt
Labels: cisco_pr, completed, complexity: medium, raw_data

#145 PR#314 IOSXE/show telemetry internal connection
  changelog/undistributed/changelog_show_telemetry_internal_connection_20201026144034.rst
  src/genie/libs/parser/iosxe/show_telemetry.py
  src/genie/libs/parser/iosxe/tests/ShowTelemetryInternalConnection/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowTelemetryInternalConnection/cli/equal/golden_output_2_expected.py
  src/genie/libs/parser/iosxe/tests/ShowTelemetryInternalConnection/cli/equal/golden_output_2_output.txt
  src/genie/libs/parser/iosxe/tests/ShowTelemetryInternalConnection/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowTelemetryInternalConnection/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low, raw_data

#130 PR#302 IOSXE/show wireless stats client detail
  changelog/undistributed/changelog_show_wireless_stats_client_detail_20201020155530.rst
  src/genie/libs/parser/iosxe/show_wireless.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessStatsClientDetail/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowWirelessStatsClientDetail/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessStatsClientDetail/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: hard
