Repository networktocode/genieparser, pull requests merged in 2020-11, with the labels that each got.

#131 PR#303 IOSXE/show wireless stats client delete reasons
  changelog/undistributed/changelog_show_wireless_stats_client_delete_reasons_20201020211550.rst
  src/genie/libs/parser/iosxe/show_wireless.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessStatsClientDeleteReasons/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowWirelessStatsClientDeleteReasons/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessStatsClientDeleteReasons/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low

#128 PR#301 IOSXE/show device tracking database int <interface>
  changelog/undistributed/changelog_show_device-tracking_database_int_20201014194519.rst
  src/genie/libs/parser/iosxe/show_device_tracking.py
  src/genie/libs/parser/iosxe/tests/ShowDeviceTrackingDatabaseInt/cli/empty/empty_output_arguments.json
  src/genie/libs/parser/iosxe/tests/ShowDeviceTrackingDatabaseInt/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowDeviceTrackingDatabaseInt/cli/equal/golden_output_arguments.json
  src/genie/libs/parser/iosxe/tests/ShowDeviceTrackingDatabaseInt/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowDeviceTrackingDatabaseInt/cli/equal/golden_output_output.txt
Labels: completed, complexity: low, raw_data

#132 PR#306 IOSXE/show cts ap sgt info {ap_name}
  changelog/undistributed/changelog_show_cts_ap_sgt_info_20201021165312.rst
  src/genie/libs/parser/iosxe/show_cts.py
  src/genie/libs/parser/iosxe/tests/ShowCtsApSgtInfo/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowCtsApSgtInfo/cli/equal/golden_output_arguments.json
  src/genie/libs/parser/iosxe/tests/ShowCtsApSgtInfo/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowCtsApSgtInfo/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low

#127 PR#298 IOSXE/show wlan id <id_number> client stats
  changelog/undistributed/changelog_show_wlan_id_client_stats_20200917180619.rst
  src/genie/libs/parser/iosxe/show_wlan.py
  src/genie/libs/parser/iosxe/tests/ShowWlanIdClientStats/cli/empty/empty_output_arguments.json
  src/genie/libs/parser/iosxe/tests/ShowWlanIdClientStats/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowWlanIdClientStats/cli/equal/golden_output_2_arguments.json
  src/genie/libs/parser/iosxe/tests/ShowWlanIdClientStats/cli/equal/golden_output_2_expected.py
  src/genie/libs/parser/iosxe/tests/ShowWlanIdClientStats/cli/equal/golden_output_2_output.txt
  src/genie/libs/parser/iosxe/tests/ShowWlanIdClientStats/cli/equal/golden_output_arguments.json
  src/genie/libs/parser/iosxe/tests/ShowWlanIdClientStats/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowWlanIdClientStats/cli/equal/golden_output_output.txt
Labels: cisco_pr, completed, complexity: hard, raw_data

#151 PR#322 IOSXE/show chassis rmi
  changelog/undistributed/changelog_show_chassis_rmi_20201028003500.rst
  src/genie/libs/parser/iosxe/show_chassis.py
  src/genie/libs/parser/iosxe/tests/ShowChassisRmi/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowChassisRmi/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowChassisRmi/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low

#134 PR#309 IOSXE/show wireless fabric vnid mapping
  changelog/undistributed/changelog_show_wireless_fabric_vnid_mapping_20201021192832.rst
  src/genie/libs/parser/iosxe/show_wireless.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessFabricVnidMapping/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowWirelessFabricVnidMapping/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowWirelessFabricVnidMapping/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low

#107 PR#263 Parser created for show snmp
  changelog/undistributed/changelog_show_snmp_20200922043104.rst
  src/genie/libs/parser/iosxe/show_snmp.py
  src/genie/libs/parser/iosxe/tests/ShowSnmp/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowSnmp/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowSnmp/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: medium, identified

#150 PR#319 IOSXE/show lisp eid-table vrf ipv4 databse
  changelog/undistributed/changelog_show_lisp_eid-table_vrf_ipv4_database_20201027181719.rst
  src/genie/libs/parser/iosxe/show_lisp.py
  src/genie/libs/parser/iosxe/tests/ShowLispEidTableVrfIpv4Database/cli/empty/empty_output_arguments.json
  src/genie/libs/parser/iosxe/tests/ShowLispEidTableVrfIpv4Database/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowLispEidTableVrfIpv4Database/cli/equal/golden_output_arguments.json
  src/genie/libs/parser/iosxe/tests/ShowLispEidTableVrfIpv4Database/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowLispEidTableVrfIpv4Database/cli/equal/golden_output_output.txt
Labels: assigned, completed, complexity: low

#141 PR#312 IOSXE/show lisp eid-table vrf User ipv4 map-cache
  changelog/undistributed/changelog_show_lisp_eid-table_vrf_User_ipv4_map-cache_20201022200342.rst
  src/genie/libs/parser/iosxe/show_lisp.py
  src/genie/libs/parser/iosxe/tests/ShowLispEidTableVrfUserIpv4MapCache/cli/empty/empty_output_arguments.json
  src/genie/libs/parser/iosxe/tests/ShowLispEidTableVrfUserIpv4MapCache/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowLispEidTableVrfUserIpv4MapCache/cli/equal/golden_output_arguments.json
  src/genie/libs/parser/iosxe/tests/ShowLispEidTableVrfUserIpv4MapCache/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowLispEidTableVrfUserIpv4MapCache/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low

#153 PR#325 IOSXE/show cts wireless profile policy {policy}
  changelog/undistributed/changelog_show_cts_wireless_profile_policy_20201029205111.rst
  src/genie/libs/parser/iosxe/show_cts.py
  src/genie/libs/parser/iosxe/tests/ShowCtsWirelessProfilePolicy/cli/empty/empty_output_arguments.json
  src/genie/libs/parser/iosxe/tests/ShowCtsWirelessProfilePolicy/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowCtsWirelessProfilePolicy/cli/equal/golden_output_arguments.json
  src/genie/libs/parser/iosxe/tests/ShowCtsWirelessProfilePolicy/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowCtsWirelessProfilePolicy/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: low

#148 PR#318 IOSXE/show lisp instance-id {instance_id} ethernet server
  changelog/undistributed/changelog_show_lisp_instance-id_ethernet_server_20201026182032.rst
  src/genie/libs/parser/iosxe/show_lisp.py
  src/genie/libs/parser/iosxe/tests/ShowLispInstanceIdEthernetServer/cli/empty/empty_output_arguments.json
  src/genie/libs/parser/iosxe/tests/ShowLispInstanceIdEthernetServer/cli/empty/empty_output_output.txt
  src/genie/libs/parser/iosxe/tests/ShowLispInstanceIdEthernetServer/cli/equal/golden_output_2_arguments.json
  src/genie/libs/parser/iosxe/tests/ShowLispInstanceIdEthernetServer/cli/equal/golden_output_2_expected.py
  src/genie/libs/parser/iosxe/tests/ShowLispInstanceIdEthernetServer/cli/equal/golden_output_2_output.txt
  src/genie/libs/parser/iosxe/tests/ShowLispInstanceIdEthernetServer/cli/equal/golden_output_3_arguments.json
  src/genie/libs/parser/iosxe/tests/ShowLispInstanceIdEthernetServer/cli/equal/golden_output_3_expected.py
  src/genie/libs/parser/iosxe/tests/ShowLispInstanceIdEthernetServer/cli/equal/golden_output_3_output.txt
  src/genie/libs/parser/iosxe/tests/ShowLispInstanceIdEthernetServer/cli/equal/golden_output_4_arguments.json
  src/genie/libs/parser/iosxe/tests/ShowLispInstanceIdEthernetServer/cli/equal/golden_output_4_expected.py
  src/genie/libs/parser/iosxe/tests/ShowLispInstanceIdEthernetServer/cli/equal/golden_output_4_output.txt
  src/genie/libs/parser/iosxe/tests/ShowLispInstanceIdEthernetServer/cli/equal/golden_output_arguments.json
  src/genie/libs/parser/iosxe/tests/ShowLispInstanceIdEthernetServer/cli/equal/golden_output_expected.py
  src/genie/libs/parser/iosxe/tests/ShowLispInstanceIdEthernetServer/cli/equal/golden_output_output.txt
Labels: assigned, cisco_pr, completed, complexity: medium, identified, raw_data
